drop table maquinaria_Activa;
drop table maquinaria_fase;
drop table maquinaria;
drop table mineral_yacimiento;
drop table mineral_mineral;
drop table pago;
drop table compra_cliente_proyecto;
drop table mineral_empresa;
drop table horario_empleado;
drop table Empleado_Fase_Cargo;
drop table Cargo_Fase;
drop table fase;
drop table etapa_explotacion;
drop table horario;
drop table usuario;
drop table empleado;
drop table permiso_rol;
drop table rol;
drop table permiso;
drop table cargo;
drop table compra_aliado;
drop table proyecto;
drop table yacimiento;
drop table compra_cliente;
drop table persona;
drop table empresa;
drop table tipo_status;
drop table mineral_presentacion;
drop table mineral;
drop table presentacion;
drop table empresa_aliada;
drop table lugar;
drop table tipo_pago;



alter sequence maquinaria_activa_id_maquinaria_activa_seq restart with 1;
alter sequence maquinaria_fase_id_maquinaria_fase_seq restart with 1;
alter sequence maquinaria_id_maquinaria_seq restart with 1;
alter sequence mineral_yacimiento_id_mineral_yacimiento_seq restart with 1;
alter sequence mineral_mineral_id_mineral_mineral_seq restart with 1;
alter sequence pago_id_pago_seq restart with 1;
alter sequence cargo_id_cargo_seq restart with 1;
alter sequence compra_cliente_proyecto_id_compra_cliente_proyecto_seq restart with 1;
alter sequence mineral_empresa_id_mineral_empresa_seq restart with 1;
alter sequence horario_empleado_id_horario_empleado_seq restart with 1;
alter sequence Empleado_Fase_Cargo_id_empleado_cargo_fase_seq restart with 1;
alter sequence Cargo_Fase_id_cargo_fase_seq restart with 1;
alter sequence fase_id_fase_seq restart with 1;
alter sequence etapa_explotacion_id_etapa_seq restart with 1;
alter sequence horario_id_horario_seq restart with 1;
alter sequence usuario_id_usuario_seq restart with 1;
alter sequence empleado_id_empleado_seq restart with 1;
alter sequence permiso_rol_id_permiso_rol_seq restart with 1;
alter sequence rol_id_rol_seq restart with 1;
alter sequence permiso_id_permiso_seq restart with 1;
alter sequence cargo_id_cargo_seq restart with 1;
alter sequence compra_aliado_id_compra_aliado_Seq restart with 1;
alter sequence proyecto_id_proyecto_seq restart with 1;
alter sequence yacimiento_id_yacimiento_seq restart with 1;
alter sequence compra_cliente_id_compra_cliente_seq restart with 1;
alter sequence persona_id_cliente_seq restart with 1;
alter sequence empresa_id_cliente_seq restart with 1;
alter sequence tipo_status_id_tipo_status_seq restart with 1;
alter sequence mineral_presentacion_id_mineral_presentacion_seq restart with 1;
alter sequence mineral_id_mineral_seq restart with 1;
alter sequence presentacion_id_presentacion_seq restart with 1;
alter sequence empresa_aliada_id_empresa_aliada_seq restart with 1;
alter sequence lugar_id_lugar_seq restart with 1;
alter sequence tipo_pago_id_tipo_pago_seq restart with 1;